apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
spec:
  template:
    spec:
      containers:
      - name: airflow-webserver
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  template:
    spec:
      containers:
      - name: airflow-scheduler
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: airflow-worker
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-triggerer
spec:
  template:
    spec:
      containers:
      - name: airflow-triggerer
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"