---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-dag-processor
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-dag-processor
  template:
    metadata:
      labels:
        app: airflow-dag-processor
    spec:
      serviceAccountName: airflow
      securityContext:
        runAsUser: 50000
        runAsGroup: 0
      # Add init container to wait for DB to be ready
      initContainers:
      - name: wait-for-db
        image: apache/airflow:3.1.0
        command:
        - /bin/bash
        - -c
        - |
          echo "Waiting for database to be initialized..."
          timeout 300s bash -c 'until airflow db check; do echo "Database not ready, waiting..."; sleep 5; done'
          echo "Database is ready!"
        env:
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-fernet-key
              key: fernet-key
        - name: AIRFLOW__API_AUTH__JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: airflow-api-secrets
              key: jwt-secret
        - name: AIRFLOW__CORE__INTERNAL_API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-api-secrets
              key: internal-api-secret-key
        envFrom:
        - configMapRef:
            name: airflow-config
      containers:
      - name: airflow-dag-processor
        image: apache/airflow:3.1.0
        command: ["airflow"]
        args: ["dag-processor"]
        env:
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-fernet-key
              key: fernet-key
        - name: AIRFLOW__API_AUTH__JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: airflow-api-secrets
              key: jwt-secret
        - name: AIRFLOW__CORE__INTERNAL_API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-api-secrets
              key: internal-api-secret-key
        envFrom:
        - configMapRef:
            name: airflow-config
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
        - name: logs
          mountPath: /opt/airflow/logs
        - name: plugins
          mountPath: /opt/airflow/plugins
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - bash
            - -c
            - 'airflow jobs check --job-type DagProcessorJob --hostname "${HOSTNAME}"'
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - 'airflow jobs check --job-type DagProcessorJob --hostname "${HOSTNAME}"'
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: dags
        persistentVolumeClaim:
          claimName: airflow-dags-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: airflow-logs-pvc
      - name: plugins
        persistentVolumeClaim:
          claimName: airflow-plugins-pvc