---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-apiserver
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-apiserver
  template:
    metadata:
      labels:
        app: airflow-apiserver
    spec:
      serviceAccountName: airflow
      securityContext:
        runAsUser: 50000
        runAsGroup: 0
      # Add init container to wait for DB to be ready
      initContainers:
      - name: wait-for-db
        image: apache/airflow:3.1.0
        command:
        - /bin/bash
        - -c
        - |
          echo "Waiting for database to be initialized..."
          timeout 300s bash -c 'until airflow db check; do echo "Database not ready, waiting..."; sleep 5; done'
          echo "Database is ready!"
        envFrom:
        - configMapRef:
            name: airflow-config
        # Then override/add secrets and specific values
        env:
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-fernet-key
              key: fernet-key
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-webserver-secret
              key: webserver-secret-key
        - name: AIRFLOW__API_AUTH__JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: airflow-api-secrets
              key: jwt-secret
        - name: AIRFLOW__CORE__INTERNAL_API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-api-secrets
              key: internal-api-secret-key
      containers:
      - name: airflow-apiserver
        image: apache/airflow:3.1.0
        command: ["airflow"]
        args: ["api-server"]
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: airflow-config
        # Then override/add secrets and specific values
        env:
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-fernet-key
              key: fernet-key
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-webserver-secret
              key: webserver-secret-key
        - name: AIRFLOW__API_AUTH__JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: airflow-api-secrets
              key: jwt-secret
        - name: AIRFLOW__CORE__INTERNAL_API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-api-secrets
              key: internal-api-secret-key
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
        - name: logs
          mountPath: /opt/airflow/logs
        - name: plugins
          mountPath: /opt/airflow/plugins
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/v2/version
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /api/v2/version
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: dags
        persistentVolumeClaim:
          claimName: airflow-dags-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: airflow-logs-pvc
      - name: plugins
        persistentVolumeClaim:
          claimName: airflow-plugins-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-apiserver
  namespace: airflow
spec:
  selector:
    app: airflow-apiserver
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP