apiVersion: v1
kind: Pod
metadata:
  name: airflow-worker
  namespace: airflow
  labels:
    tier: airflow
    component: worker
    release: airflow
spec:
  serviceAccountName: airflow-worker
  restartPolicy: Never
  containers:
    - name: base
      image: apache/airflow:3.1.0
      envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-secrets
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
      volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
          readOnly: true
        - name: logs
          mountPath: /opt/airflow/logs
        - name: pod-template
          mountPath: /opt/airflow/pod_templates
  volumes:
    - name: dags
      persistentVolumeClaim:
        claimName: airflow-dags-pvc
    - name: logs
      persistentVolumeClaim:
        claimName: airflow-logs-pvc
    - name: pod-template
      configMap:
        name: pod-template-configmap