apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  namespace: airflow
type: Opaque
data:
  fernet-key: NFNOSHR4Mzd4WkZuUm54TlpkaE8wSmlMSDBscTZ4UF9od3lFdDA2RVdoUT0=

---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret
  namespace: airflow
type: Opaque
data:
  webserver-secret-key: UkZybFNUNjE1VW0xeEl3MnRRbHlUZkQzNDBmV19pVkxnMlFESTJ2Zzk2SQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-api-secrets
  namespace: airflow
type: Opaque
data:
  jwt-secret: Zk1xTWVBenFGbXhjOURNR29VNTNjUT09
  internal-api-secret-key: RUhpc29EX25oZGxDMlU3Y0VMU0FvZmtINVR5OXNmMEhoQ1M5ZzQzVU1fWQ==