apiVersion: v1
kind: Namespace
metadata:
  name: airflow
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: airflow
data:
  AIRFLOW__CORE__EXECUTOR: "CeleryExecutor"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgresql-service:5432/airflow"
  AIRFLOW__CORE__FERNET_KEY: "your-fernet-key-here-32-bytes-base64-encoded"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
  AIRFLOW__CELERY__BROKER_URL: "redis://redis-service:6379/0"
  AIRFLOW__CELERY__RESULT_BACKEND: "redis://redis-service:6379/0"
  AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "30"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  AIRFLOW__WEBSERVER__AUTHENTICATE: "True"
  AIRFLOW__WEBSERVER__INSTANCE_NAME: "Airflow"
  AIRFLOW__LOGGING__BASE_LOG_FOLDER: "/opt/airflow/logs"
  AIRFLOW__CORE__PLUGINS_FOLDER: "/opt/airflow/plugins"
  AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: airflow
type: Opaque
data:
  AIRFLOW__CORE__FERNET_KEY: eW91ci1mZXJuZXQta2V5LWhlcmUqKioqKioqKioqKioqKioqKioqKio=  # your-fernet-key-here***************
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: cG9zdGdyZXNxbCtwc3ljb3BnMjovL2FpcmZsb3c6YWlyZmxvd0Bwb3N0Z3Jlc3FsLXNlcnZpY2U6NTQzMi9haXJmbG93  # postgresql+psycopg2://airflow:airflow@postgresql-service:5432/airflow
  POSTGRES_PASSWORD: YWlyZmxvdw==  # airflow
  POSTGRES_USER: YWlyZmxvdw==  # airflow
  POSTGRES_DB: YWlyZmxvdw==  # airflow
  REDIS_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret
  namespace: airflow
type: Opaque
data:
  AIRFLOW__WEBSERVER__SECRET_KEY: eW91ci1zZWNyZXQta2V5LWhlcmUtd2ViLXNlcnZlcg==  # your-secret-key-here-web-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: airflow
  labels:
    app: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      serviceAccountName: airflow
      containers:
      - name: airflow-webserver
        image: apache/airflow:2.10.2-python3.11
        imagePullPolicy: IfNotPresent
        command:
          - airflow
          - webserver
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-secrets
        - secretRef:
            name: airflow-webserver-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        volumeMounts:
        - name: dags-volume
          mountPath: /opt/airflow/dags
        - name: logs-volume
          mountPath: /opt/airflow/logs
        - name: plugins-volume
          mountPath: /opt/airflow/plugins
      volumes:
      - name: dags-volume
        persistentVolumeClaim:
          claimName: airflow-dags-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: airflow-logs-pvc
      - name: plugins-volume
        persistentVolumeClaim:
          claimName: airflow-plugins-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-service
  namespace: airflow
spec:
  selector:
    app: airflow-webserver
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
  labels:
    app: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      serviceAccountName: airflow
      containers:
      - name: airflow-scheduler
        image: apache/airflow:2.10.2-python3.11
        imagePullPolicy: IfNotPresent
        command:
          - airflow
          - scheduler
        envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        volumeMounts:
        - name: dags-volume
          mountPath: /opt/airflow/dags
        - name: logs-volume
          mountPath: /opt/airflow/logs
        - name: plugins-volume
          mountPath: /opt/airflow/plugins
      volumes:
      - name: dags-volume
        persistentVolumeClaim:
          claimName: airflow-dags-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: airflow-logs-pvc
      - name: plugins-volume
        persistentVolumeClaim:
          claimName: airflow-plugins-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  namespace: airflow
  labels:
    app: airflow-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airflow-worker
  template:
    metadata:
      labels:
        app: airflow-worker
    spec:
      serviceAccountName: airflow
      containers:
      - name: airflow-worker
        image: apache/airflow:2.10.2-python3.11
        imagePullPolicy: IfNotPresent
        command:
          - airflow
          - celery
          - worker
        envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        volumeMounts:
        - name: dags-volume
          mountPath: /opt/airflow/dags
        - name: logs-volume
          mountPath: /opt/airflow/logs
        - name: plugins-volume
          mountPath: /opt/airflow/plugins
      volumes:
      - name: dags-volume
        persistentVolumeClaim:
          claimName: airflow-dags-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: airflow-logs-pvc
      - name: plugins-volume
        persistentVolumeClaim:
          claimName: airflow-plugins-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-triggerer
  namespace: airflow
  labels:
    app: airflow-triggerer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-triggerer
  template:
    metadata:
      labels:
        app: airflow-triggerer
    spec:
      serviceAccountName: airflow
      containers:
      - name: airflow-triggerer
        image: apache/airflow:2.10.2-python3.11
        imagePullPolicy: IfNotPresent
        command:
          - airflow
          - triggerer
        envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: dags-volume
          mountPath: /opt/airflow/dags
        - name: logs-volume
          mountPath: /opt/airflow/logs
      volumes:
      - name: dags-volume
        persistentVolumeClaim:
          claimName: airflow-dags-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: airflow-logs-pvc
---
apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init-db
  namespace: airflow
  labels:
    app: airflow-init-db
spec:
  template:
    spec:
      serviceAccountName: airflow
      containers:
      - name: airflow-init
        image: apache/airflow:2.10.2-python3.11
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args:
          - |
            airflow db init
            airflow users create \
              --username admin \
              --firstname Airflow \
              --lastname Admin \
              --role Admin \
              --email admin@example.com \
              --password admin
        envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      restartPolicy: OnFailure
  backoffLimit: 3
---
apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-migrate-db
  namespace: airflow
  labels:
    app: airflow-migrate-db
spec:
  template:
    spec:
      serviceAccountName: airflow
      containers:
      - name: airflow-migrate
        image: apache/airflow:2.10.2-python3.11
        imagePullPolicy: IfNotPresent
        command: ["airflow", "db", "migrate"]
        envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      restartPolicy: OnFailure
  backoffLimit: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: airflow
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: POSTGRES_DB
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - airflow
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - airflow
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: airflow-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: airflow
spec:
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-postgres-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: airflow
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: airflow
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  namespace: airflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow
  namespace: airflow
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status"]
  verbs: ["get", "list", "watch", "delete", "create", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "delete", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow
  namespace: airflow
subjects:
- kind: ServiceAccount
  name: airflow
  namespace: airflow
roleRef:
  kind: Role
  name: airflow
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-plugins-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi